### ISSUE TITLE
Possible to download playlists

### ISSUE THREAD

**Issue by naqushab** [arunKumarNOP/Saavn-Downloader-Android#1]
Is it possible to make a custom playlist and share that to your app for downloading that. I tried it but your app crashed without any specific information.

**Comment by arunKumarNOP** [comment]
I have not tried with custom playlist so i am not sure how the app would behave. Can you share one such playlist so that i can test and fix it.

**Comment by naqushab** [comment]
Like this: http://www.saavn.com/s/playlist/naqushabneyazee713/10Nov2016/M5LnEFJNGQw_
This is a playlist created by me.

**Comment by santosh-hegde** [comment]
App is crashing in Mi phone

**Comment by arunKumarNOP** [comment]
Fixed the playlist issue see this commit [be7fe12](https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/be7fe12d2b1c4b7cfb412198da2c68e3e2a39c39)

@santosh-hegde - Open a new issue and provide details like what you were trying to do when the app crashed and possibly post the logcat when the crashed occured.

Closing this issue
