### ISSUE TITLE
Only m4a downloading

### ISSUE THREAD

**Issue by Shiv659** [arunKumarNOP/Saavn-Downloader-Android#2]
The project is not building on my pc. used release version, it crashed 2 times while returning from settings.
Slow download speed 
and please if possible add support to download mp3.
Good job :+1:

**Comment by arunKumarNOP** [comment]
* Oh sorry about that build thing actually i had my college proxy set maybe thats why it wasn't building. I have removed it from the 'gradle.properties' file and now hopefully now you can build.

* About the crash, please post the logcat so i can trace the culprit.

* Slow Download - I can sending the download request to Android Download Manager, its used even by chrome to download files by default so i think the problem might be in you connection, once try on different connection.

* Support for mp3 - the server sends m4a so i am downloading in m4a format, to download in mp3 one has to download in m4a and then convert it to mp3 which can be done by using FFMpeg library but i think m4a is better in both quality and file size and almost every device now support m4a format, if you still think thats important then let me know.

Regards

**Comment by Shiv659** [comment]
Ok, I'll try to build and send the logcat.
I've downloaded only one song I'll try more maybe at the moment network was unstable.
mp3 is not necessary, most of the devices support m4a but most players don't.
