### ISSUE TITLE
App not list songs with latest Saavn pack

### ISSUE THREAD

**Issue by SArun61** [arunKumarNOP/Saavn-Downloader-Android#4]
From yesterday onwards app could not retrieve the songs list to download further. I guess Saavn is securing some data. Kindly check it out.

**Comment by arunKumarNOP** [comment]
Fixed it in this commit https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/ef1b3b40c98b559601be0e4422b9021930d729a9

**Comment by SArun61** [comment]
Dear Arun,
 Kudos to you. :-)

Regards,
Arun. S,
+91-9500162255.

**Comment by jatinverms8800** [comment]
How to download your app

**Comment by jatinverms8800** [comment]
I have you app....but i face same problem...

**Comment by arunKumarNOP** [comment]
Works fine with v5.7.1.
