### ISSUE TITLE
No album art

### ISSUE THREAD

**Issue by omendra9** [arunKumarNOP/Saavn-Downloader-Android#6]
Everything is perfect please do something for album art. 
really nice app.

**Comment by arunKumarNOP** [comment]
Added this capability in this commit https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/ec0eba79d7bfedeb42530e6a30b8d0edea938207

Check the Pre-release in the release section and let me know of any issues.

**Comment by AkSachin** [comment]
currentSong.getAlbumArtUrl() in DownloadService.java gives lower quality album art which is 150x150 image which looks blurry even in phone screen.

This is an example link that it gives :
http://c.saavncdn.com/511/Jagga-Jasoos-Hindi-2017-150x150.jpg

You can replace 150x150 to 500x500 for better quality image.
Also can you please imbed Album name, Artist names and Year in the file itself just like Album art ?

**Comment by AkSachin** [comment]
Just found that app already embeds Album name, Artists names and Year in the song file. My Bad.

**Comment by arunKumarNOP** [comment]
Ok increased the resolution of album art to 150x150 to 500x500 https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/9e69d3bd52e5c0ce18a357caae3aa79897980d5f hacky way but should work just fine.

Let me know if it work, then i will add it to release section.

**Comment by AkSachin** [comment]
Yes, It works.

**Comment by arunKumarNOP** [comment]
Ok its updated in release section.

**Comment by omendra9** [comment]
perfect !!! thanks a lot :D <3
