### ISSUE TITLE
Embed title

### ISSUE THREAD

**Issue by AkSachin** [arunKumarNOP/Saavn-Downloader-Android#7]
Please can you embed the Title of the song in the file itself just like Artist, Album ?
I tried myself but ended in messing things up.

Also the songs downloaded with your app is shown in Unknown Artists category in music player apps.
(Tried using Google Play Music and My handset's default music player)
But if I move the songs from their downloaded folder to another location, the artists names gets shown in the category in the apps.
If this is the same case with you too then it should get resolved.

**Comment by arunKumarNOP** [comment]
Added title of the song in https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/9b05e7738db5cac8a1801a08218956bea3216c35 commit.

In my case i can't confirm the Unknown Artists issue, i use VLC android and it updates without any intervention.

I think it might be MediaServer is not updating its database so i have added code to refresh it when new media is downloaded. Check it and let me know if it works or not.

**Comment by AkSachin** [comment]
Thanks for adding the title.

It still shows Unknown Artist in Google Play Music. But I guess I'll use VLC. So it's alright.
