### ISSUE TITLE
High Quality Downloades Music Cover and Artist missing

### ISSUE THREAD

**Issue by Pakeetharan** [arunKumarNOP/Saavn-Downloader-Android#8]
While downloading in high quality .m4a format there is no artists or album art, and low quality .mp3 just works fine with all details. Please bring the same to .m4a format high quality songs.

**Comment by arunKumarNOP** [comment]
The app does fixes artists and album art whether its high quality or low quality song.

Please share song link which you were trying and android version. I tested it on API level 19, 21 and 23 and works fine with any link.

**Comment by Pakeetharan** [comment]
https://www.saavn.com/s/song/tamil/En-Aaloda-Seruppa-Kaanom/Iravil-Varukira-Female/OxASXAxBZV4

**Comment by arunKumarNOP** [comment]
Ahh i see, i never thought that artist map will be empty. The artist name was set to null when artist map was empty i fixed it this commit https://github.com/arunKumarNOP/Saavn-Downloader-Android/commit/9f57e67bf4f80edad99d726618a6a7f646bb4f64 check it and let me know.

**Comment by Pakeetharan** [comment]
Release a new build :)

**Comment by arunKumarNOP** [comment]
Releasing a new build after every commit is not feasible, i recommend to get gradle to compile the source code and test it.

I will add a release later on.
