### ISSUE TITLE
Same quality .m4a and .mp3

### ISSUE THREAD

**Issue by Pakeetharan** [arunKumarNOP/Saavn-Downloader-Android#9]
What's the difference between the high size .m4a and small size .mp3 downloaded through the downloader????
Same but size upscaled?? Not the High Quality Download?? Just Saavn faking the Users??

Proof: 

Song: https://www.saavn.com/s/song/tamil/Sema/Sandalee/HjcZdz8Eflw

.M4A SPEK http://imgur.com/QVd3dzv
.Mp3 SPEK http://imgur.com/II3EIPJ

Is this with Saavn or what?

**Comment by Pakeetharan** [comment]
Another One:
Saavn Direct MP3 http://imgur.com/jHkXrAr
Saavn Downloader M4A http://imgur.com/FPoF1an

**Comment by arunKumarNOP** [comment]
As far as i know mp3 is lossy whereas m4a is lossless thats why the size difference. Human ears cannot tell the difference.

I think Saavn want to preserve the quality rather than worry about size.

**Comment by Pakeetharan** [comment]
As far as I know .m4a is just a container, here it's lossy AAC. No size difference I found, but the same SPEK result for m4a 320kbps and mp3 128kbps, does that make any sense???

**Comment by arunKumarNOP** [comment]
I don't know why Saavn servers did that, they will have some reason behind it.

Frankly speaking i don't care if i spent few more MBs to get a song (though i don't listen to songs much) :p
